#!/bin/bash
set -e


PHP_ERROR_REPORTING=${PHP_ERROR_REPORTING:-"E_ALL & ~E_DEPRECATED & ~E_NOTICE"}
sed -ri 's/^display_errors\s*=\s*Off/display_errors = On/g' /etc/php/5.6/apache2/php.ini
sed -ri 's/^display_errors\s*=\s*Off/display_errors = On/g' /etc/php/5.6/cli/php.ini
sed -ri "s/^error_reporting\s*=.*$//g" /etc/php/5.6/apache2/php.ini
sed -ri "s/^error_reporting\s*=.*$//g" /etc/php/5.6/cli/php.ini
echo "error_reporting = $PHP_ERROR_REPORTING" >> /etc/php/5.6/apache2/php.ini
echo "error_reporting = $PHP_ERROR_REPORTING" >> /etc/php/5.6/cli/php.ini

# Note: we don't just use "apache2ctl" here because it itself is just a shell-script wrapper around apache2 which provides extra functionality like "apache2ctl start" for launching apache2 in the background.
# (also, when run as "apache2ctl <apache args>", it does not use "exec", which leaves an undesirable resident shell process)

: "${APACHE_CONFDIR:=/etc/apache2}"
: "${APACHE_ENVVARS:=$APACHE_CONFDIR/envvars}"
if test -f "$APACHE_ENVVARS"; then
	. "$APACHE_ENVVARS"
fi

# Apache gets grumpy about PID files pre-existing
: "${APACHE_PID_FILE:=${APACHE_RUN_DIR:=/var/run/apache2}/apache2.pid}"
rm -f "$APACHE_PID_FILE"

exec apache2 -DFOREGROUND "$@"
